# Generated by Django 5.2.3 on 2026-06-14 07:31

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model("app", "Role")

    Role.objects.get_or_create(role="admin")
    Role.objects.get_or_create(role="manager")
    Role.objects.get_or_create(role="employee")


def delete_roles(apps, schema_editor):
    Role = apps.get_model("app", "Role")

    Role.objects.filter(role__in=[
        "admin",
        "manager",
        "employee"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_roles,
            reverse_code=delete_roles
        ),
    ]